// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3M0k0HSifpI7M4xJImNiF9mtmHXu16dk',
    appId: '1:479484882113:web:32276b9eca0bfd35657840',
    messagingSenderId: '479484882113',
    projectId: 'voiceassistant-418ac',
    authDomain: 'voiceassistant-418ac.firebaseapp.com',
    storageBucket: 'voiceassistant-418ac.appspot.com',
    measurementId: 'G-V34P453GLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwHVxjwiUaWADY2mW1wlJEdJn2ysHKjCo',
    appId: '1:479484882113:android:0b8e5ca29d8a6be6657840',
    messagingSenderId: '479484882113',
    projectId: 'voiceassistant-418ac',
    storageBucket: 'voiceassistant-418ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aATRCw_0JzYQgkszJDDzeRvuFj3C9zA',
    appId: '1:479484882113:ios:b93a43c927f6c862657840',
    messagingSenderId: '479484882113',
    projectId: 'voiceassistant-418ac',
    storageBucket: 'voiceassistant-418ac.appspot.com',
    iosClientId: '479484882113-t3vir6tc3ap1i9qatkmja9mtrldq4aij.apps.googleusercontent.com',
    iosBundleId: 'com.example.assistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7aATRCw_0JzYQgkszJDDzeRvuFj3C9zA',
    appId: '1:479484882113:ios:b93a43c927f6c862657840',
    messagingSenderId: '479484882113',
    projectId: 'voiceassistant-418ac',
    storageBucket: 'voiceassistant-418ac.appspot.com',
    iosClientId: '479484882113-t3vir6tc3ap1i9qatkmja9mtrldq4aij.apps.googleusercontent.com',
    iosBundleId: 'com.example.assistant',
  );
}
