// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGdL8XYXOsd0ue926MHCKcPGRpRG0AL5o',
    appId: '1:222109122458:web:def9e2c1caa88b40d38423',
    messagingSenderId: '222109122458',
    projectId: 'voice-assistant-7c535',
    authDomain: 'voice-assistant-7c535.firebaseapp.com',
    storageBucket: 'voice-assistant-7c535.appspot.com',
    measurementId: 'G-RBL27R11XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4srgigUJT-o1UPbzM3tLXGNYd7Wf_e7k',
    appId: '1:222109122458:android:f321f55d4961c586d38423',
    messagingSenderId: '222109122458',
    projectId: 'voice-assistant-7c535',
    storageBucket: 'voice-assistant-7c535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaOLZcYYI8hCK9DNx0BwgA86ZGTf_FEeY',
    appId: '1:222109122458:ios:1eb64a2251953cecd38423',
    messagingSenderId: '222109122458',
    projectId: 'voice-assistant-7c535',
    storageBucket: 'voice-assistant-7c535.appspot.com',
    iosClientId: '222109122458-acai1hg4oq07rkdo9h6jnnsksjd4crfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.assistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaOLZcYYI8hCK9DNx0BwgA86ZGTf_FEeY',
    appId: '1:222109122458:ios:1eb64a2251953cecd38423',
    messagingSenderId: '222109122458',
    projectId: 'voice-assistant-7c535',
    storageBucket: 'voice-assistant-7c535.appspot.com',
    iosClientId: '222109122458-acai1hg4oq07rkdo9h6jnnsksjd4crfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.assistant',
  );
}
